// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./components/BaseButton.vue')['default']
    BaseIcon: typeof import('./components/BaseIcon.vue')['default']
    Card: typeof import('./components/Card.vue')['default']
    EssentialLink: typeof import('./components/EssentialLink.vue')['default']
    ExampleComponent: typeof import('./components/ExampleComponent.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    MyLink: typeof import('./components/myLink.vue')['default']
    PopularCards: typeof import('./components/PopularCards.vue')['default']
    Radio: typeof import('./components/Radio.vue')['default']
    TabBody: typeof import('./components/TabBody.vue')['default']
    TabContent: typeof import('./components/TabContent.vue')['default']
    TabItem: typeof import('./components/TabItem.vue')['default']
    TabItemList: typeof import('./components/TabItemList.vue')['default']
  }
}

export { }
